In [1]:
import pandas as pd
import numpy as np
import pyreadr
import plotly.express as px
import plotly.graph_objects as go

In [11]:
#read in old unit data at lsoa level
file_path = '/Users/user1/Downloads/ldd_backseries_dwellings_LSOA11CD.rds'

# Read the file
result = pyreadr.read_r(file_path)

# Get the data frame from the returned dictionary
lsoa_unit_data_old = result[None]  # None is the key for the unnamed object in the RDS file

# Show the first few rows
lsoa_unit_data_old.head()

     year gss_code_lsoa   units
0  2011.0     E01000001  1012.0
1  2011.0     E01000002   975.0
2  2011.0     E01000003   886.0
3  2011.0     E01000005   528.0
4  2011.0     E01000006   558.0

In [12]:
lsoa_unit_data_old

         year gss_code_lsoa   units
0      2011.0     E01000001  1012.0
1      2011.0     E01000002   975.0
2      2011.0     E01000003   886.0
3      2011.0     E01000005   528.0
4      2011.0     E01000006   558.0
...       ...           ...     ...
43510  2019.0     E01033742     0.0
43511  2019.0     E01033743     0.0
43512  2019.0     E01033744     0.0
43513  2019.0     E01033745     0.0
43514  2019.0     E01033746     0.0

[43515 rows x 3 columns]

In [2]:
df = lsoa_unit_data_old.copy()

# Get unique LSOA codes
lsoa_list = df['gss_code_lsoa'].unique()

# Create the figure
fig = go.Figure()

# Add a default trace (first LSOA)
default_lsoa = lsoa_list[0]
df_default = df[df['gss_code_lsoa'] == default_lsoa]
fig.add_trace(go.Scatter(
    x=df_default['year'],
    y=df_default['units'],
    mode='lines+markers',
    name=default_lsoa
))

# Create dropdown buttons
dropdown_buttons = []

for lsoa in lsoa_list:
    df_temp = df[df['gss_code_lsoa'] == lsoa]
    dropdown_buttons.append(dict(
        method='update',
        label=lsoa,
        args=[
            {'x': [df_temp['year']],
             'y': [df_temp['units']],
             'type': 'scatter'},
            {'title': f'Units Over Time — {lsoa}'}
        ]
    ))

# Update layout with dropdown menu
fig.update_layout(
    title=f'Units Over Time — {default_lsoa}',
    xaxis_title='Year',
    yaxis_title='Unit Count',
    updatemenus=[dict(
        active=0,
        buttons=dropdown_buttons,
        direction='down',
        x=0.1,
        xanchor='left',
        y=1.15,
        yanchor='top',
        showactive=True
    )]
)

fig.show()

NameError: name 'lsoa_unit_data_old' is not defined

In [4]:
# Read in the new data at OA level
new_data_path = '/Users/user1/Documents/recoding_adress_data_2011_2021/london_data/oa_adress_counts.csv'
oa_adress_data_new = pd.read_csv(new_data_path)

In [89]:
oa_adress_data_new

,OA21CD,LSOA21CD,LSOA21NM,borough,year,address_count_oa,WD24CD,WD24NM,WD24NMW,LAD24CD,LAD24NM,LAD24NMW,ObjectId,address_count_ward,oa_yoy_pct_change,ward_yoy_pct_change
0,E00000001,E01000001,City of London 001A,City of London,2011,116,E05009288,Aldersgate,NaN,E09000001,City of London,NaN,152354,1308,NaN,NaN
1,E00000001,E01000001,City of London 001A,City of London,2012,116,E05009288,Aldersgate,NaN,E09000001,City of London,NaN,152354,1308,0.000000,0.000000
2,E00000001,E01000001,City of London 001A,City of London,2013,116,E05009288,Aldersgate,NaN,E09000001,City of London,NaN,152354,1308,0.000000,0.000000
3,E00000001,E01000001,City of London 001A,City of London,2014,116,E05009288,Aldersgate,NaN,E09000001,City of London,NaN,152354,1311,0.000000,0.229358
4,E00000001,E01000001,City of London 001A,City of London,2015,116,E05009288,Aldersgate,NaN,E09000001,City of London,NaN,152354,1311,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367556,E00190469,E01035709,Camden 022G,Camden,2020,108,E05013669,St Pancras & Somers Town,NaN,E09000007,Camden,NaN,157320,6678,0.000000,0.000000
367557,E00190469,E01035709,Camden 022G,Camden,2021,108,E05013669,St Pancras & Somers Town,NaN,E09000007,Camden,NaN,157320,6756,0.000000,1.168014
367558,E00190469,E01035709,Camden 022G,Camden,2022,108,E05013669,St Pancras & Somers Town,NaN,E09000007,Camden,NaN,157320,6895,0.000000,2.057430
367559,E00190469,E01035709,Camden 022G,Camden,2023,108,E05013669,St Pancras & Somers Town,NaN,E09000007,Camden,NaN,157320,6929,0.000000,0.493111
367560,E00190469,E01035709,Camden 022G,Camden,2024,105,E05013669,St Pancras & Somers Town,NaN,E09000007,Camden,NaN,157320,6955,-2.777778,0.375235

In [113]:
oa_adress_data_new_filtered = oa_adress_data_new.drop(['WD24NMW'], axis=1)
oa_adress_data_new_filtered

,OA21CD,LSOA21CD,LSOA21NM,borough,year,address_count_oa,WD24CD,WD24NM,LAD24CD,LAD24NM,LAD24NMW,ObjectId,address_count_ward,oa_yoy_pct_change,ward_yoy_pct_change
0,E00000001,E01000001,City of London 001A,City of London,2011,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1308,NaN,NaN
1,E00000001,E01000001,City of London 001A,City of London,2012,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1308,0.000000,0.000000
2,E00000001,E01000001,City of London 001A,City of London,2013,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1308,0.000000,0.000000
3,E00000001,E01000001,City of London 001A,City of London,2014,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1311,0.000000,0.229358
4,E00000001,E01000001,City of London 001A,City of London,2015,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1311,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367556,E00190469,E01035709,Camden 022G,Camden,2020,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6678,0.000000,0.000000
367557,E00190469,E01035709,Camden 022G,Camden,2021,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6756,0.000000,1.168014
367558,E00190469,E01035709,Camden 022G,Camden,2022,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6895,0.000000,2.057430
367559,E00190469,E01035709,Camden 022G,Camden,2023,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6929,0.000000,0.493111
367560,E00190469,E01035709,Camden 022G,Camden,2024,105,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6955,-2.777778,0.375235

In [123]:
# Sort the data
oa_adress_data_new_filtered = oa_adress_data_new_filtered.sort_values(by=['OA21CD', 'year'])

# Compute difference
oa_adress_data_new_filtered['oa_address_added'] = oa_adress_data_new_filtered.groupby('OA21CD')['address_count_oa'].diff()

# Replace the first NaN in each group with the original count
first_counts = oa_adress_data_new_filtered.groupby('OA21CD')['address_count_oa'].transform('first')
oa_adress_data_new_filtered['oa_address_added'] = oa_adress_data_new_filtered['oa_address_added'].fillna(first_counts).astype(int)

#ward count difference
oa_adress_data_new_filtered['ward_address_added'] = oa_adress_data_new_filtered.groupby('WD24CD')['address_count_ward'].diff()
# Replace the first NaN in each group with the original count
first_counts_ward = oa_adress_data_new_filtered.groupby('WD24CD')['address_count_ward'].transform('first')
oa_adress_data_new_filtered['ward_address_added'] = oa_adress_data_new_filtered['ward_address_added'].fillna(first_counts_ward).astype(int)

In [124]:
oa_adress_data_new_filtered

,OA21CD,LSOA21CD,LSOA21NM,borough,year,address_count_oa,WD24CD,WD24NM,LAD24CD,LAD24NM,LAD24NMW,ObjectId,address_count_ward,oa_yoy_pct_change,ward_yoy_pct_change,oa_address_added,ward_address_added
0,E00000001,E01000001,City of London 001A,City of London,2011,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1308,NaN,NaN,116,1308
1,E00000001,E01000001,City of London 001A,City of London,2012,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1308,0.000000,0.000000,0,0
2,E00000001,E01000001,City of London 001A,City of London,2013,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1308,0.000000,0.000000,0,0
3,E00000001,E01000001,City of London 001A,City of London,2014,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1311,0.000000,0.229358,0,3
4,E00000001,E01000001,City of London 001A,City of London,2015,116,E05009288,Aldersgate,E09000001,City of London,NaN,152354,1311,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367556,E00190469,E01035709,Camden 022G,Camden,2020,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6678,0.000000,0.000000,0,0
367557,E00190469,E01035709,Camden 022G,Camden,2021,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6756,0.000000,1.168014,0,78
367558,E00190469,E01035709,Camden 022G,Camden,2022,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6895,0.000000,2.057430,0,139
367559,E00190469,E01035709,Camden 022G,Camden,2023,108,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6929,0.000000,0.493111,0,34
367560,E00190469,E01035709,Camden 022G,Camden,2024,105,E05013669,St Pancras & Somers Town,E09000007,Camden,NaN,157320,6955,-2.777778,0.375235,-3,26

In [126]:
oa_adress_data_new_filtered
#save csv
oa_adress_data_new_filtered.to_csv('/Users/user1/Documents/recoding_adress_data_2011_2021/london_data/oa_and_ward_address_counts.csv', index=False)

In [ ]:
oa_adress_data_new
#sum address counts oa by LSOA21CD and year
lsoa_adress_data = oa_adress_data_new.groupby(['LSOA21CD', 'year'])['address_count_oa'].sum().reset_index()

In [8]:
lsoa_adress_data

        LSOA21CD  year  address_count_oa
0      E01000001  2011              1067
1      E01000001  2012              1067
2      E01000001  2013              1067
3      E01000001  2014              1070
4      E01000001  2015              1070
...          ...   ...               ...
69862  E01035722  2020              2023
69863  E01035722  2021              2026
69864  E01035722  2022              2024
69865  E01035722  2023              2010
69866  E01035722  2024              2009

[69867 rows x 3 columns]

In [18]:
lsoa_adress_data = lsoa_adress_data.sort_values(by=['LSOA21CD', 'year'])

# Compute annual address additions
lsoa_adress_data['address_added'] = lsoa_adress_data.groupby('LSOA21CD')['address_count_oa'].diff().fillna(0).astype(int)

In [29]:
# Sort the data
lsoa_adress_data = lsoa_adress_data.sort_values(by=['LSOA21CD', 'year'])

# Compute difference
lsoa_adress_data['address_added'] = lsoa_adress_data.groupby('LSOA21CD')['address_count_oa'].diff()

# Replace the first NaN in each group with the original count
first_counts = lsoa_adress_data.groupby('LSOA21CD')['address_count_oa'].transform('first')
lsoa_adress_data['address_added'] = lsoa_adress_data['address_added'].fillna(first_counts).astype(int)

In [19]:
lsoa_adress_data

        LSOA21CD  year  address_count_oa  address_added
0      E01000001  2011              1067              0
1      E01000001  2012              1067              0
2      E01000001  2013              1067              0
3      E01000001  2014              1070              3
4      E01000001  2015              1070              0
...          ...   ...               ...            ...
69862  E01035722  2020              2023              6
69863  E01035722  2021              2026              3
69864  E01035722  2022              2024             -2
69865  E01035722  2023              2010            -14
69866  E01035722  2024              2009             -1

[69867 rows x 4 columns]

In [54]:
# First, standardize column names and types
df1 = lsoa_adress_data.rename(columns={
    'LSOA21CD': 'lsoa',
    'year': 'year',
    'address_count_oa': 'address_count',
    'address_added_oa': 'address_added'
})

df2 = lsoa_unit_data_old.rename(columns={
    'gss_code_lsoa': 'lsoa',
    'year': 'year',
    'units': 'unit_count'
})

# Make sure year is int and not float
df2['year'] = df2['year'].astype(int)

# Merge the two DataFrames on lsoa and year
merged_df = df1.merge(df2, on=['lsoa', 'year'], how='inner')

# Add a new column to compare
merged_df['address_minus_units'] = merged_df['address_count'] - merged_df['unit_count']
merged_df['address_to_unit_ratio'] = merged_df['address_count'] / merged_df['unit_count']

# Preview result
merged_df.head()

,lsoa,year,address_count,address_added,unit_count,address_minus_units,address_to_unit_ratio
0,E01000001,2011,1067,1067,1012.0,55.0,1.054348
1,E01000001,2012,1067,0,0.0,1067.0,inf
2,E01000001,2013,1067,0,0.0,1067.0,inf
3,E01000001,2014,1070,3,3.0,1067.0,356.666667
4,E01000001,2015,1070,0,-1.0,1071.0,-1070.000000

In [55]:
# Summary stats
merged_df[['address_count','address_added','unit_count', 'address_minus_units', 'address_to_unit_ratio']].describe()

/opt/anaconda3/envs/env/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning:

invalid value encountered in subtract

/opt/anaconda3/envs/env/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:4669: RuntimeWarning:

invalid value encountered in subtract

,address_count,address_added,unit_count,address_minus_units,address_to_unit_ratio
count,41931.000000,41931.000000,41931.000000,41931.000000,4.193100e+04
mean,739.020295,84.691827,80.484635,658.535660,inf
std,191.513529,233.236720,221.327582,286.909319,NaN
min,246.000000,-408.000000,-990.710957,-523.018339,-3.526319e+18
25%,621.000000,0.000000,0.000000,575.000000,3.654426e+01
50%,699.000000,1.000000,0.000000,677.000000,6.430000e+02
75%,821.000000,7.000000,5.000000,800.000000,NaN
max,3524.000000,2479.000000,1744.000000,3516.000000,inf

In [1]:
# Use the merged DataFrame from before
# merged_df contains columns: lsoa, year, address_count, unit_count

# Get unique LSOA codes
lsoa_list = merged_df['lsoa'].unique()

# Create figure
fig = go.Figure()

# Add traces for the first LSOA as default
default_lsoa = lsoa_list[0]
df_filtered = merged_df[merged_df['lsoa'] == default_lsoa]

fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['address_count'],
    mode='lines+markers',
    name='Address Count'
))

fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['unit_count'],
    mode='lines+markers',
    name='Unit Count'
))

# Add dropdown menu to select LSOA
dropdown_buttons = []

for lsoa in lsoa_list:
    df_temp = merged_df[merged_df['lsoa'] == lsoa]
    
    address_trace = go.Scatter(
        x=df_temp['year'],
        y=df_temp['address_count'],
        mode='lines+markers',
        name='Address Count'
    )
    
    unit_trace = go.Scatter(
        x=df_temp['year'],
        y=df_temp['unit_count'],
        mode='lines+markers',
        name='Unit Count'
    )
    
    dropdown_buttons.append(
        dict(
            method='update',
            label=lsoa,
            args=[{'x': [df_temp['year'], df_temp['year']],
                   'y': [df_temp['address_count'], df_temp['unit_count']]},
                  {'title': f"Address vs Units over Time — {lsoa}"}]
        )
    )

# Update layout
fig.update_layout(
    title=f"Address vs Units over Time — {default_lsoa}",
    xaxis_title="Year",
    yaxis_title="Count",
    updatemenus=[{
        "buttons": dropdown_buttons,
        "direction": "down",
        "showactive": True,
        "x": 0.1,
        "xanchor": "left",
        "y": 1.15,
        "yanchor": "top"
    }]
)

fig.show()

NameError: name 'merged_df' is not defined

In [53]:
merged_df

,lsoa,year,address_count,address_added,unit_count,address_minus_units,address_to_unit_ratio
0,E01000001,2011,1067,0,1.012000e+03,55.0,1.054348e+00
1,E01000001,2012,1067,0,0.000000e+00,1067.0,inf
2,E01000001,2013,1067,0,0.000000e+00,1067.0,inf
3,E01000001,2014,1070,3,3.000000e+00,1067.0,3.566667e+02
4,E01000001,2015,1070,0,-1.000000e+00,1071.0,-1.070000e+03
...,...,...,...,...,...,...,...
41926,E01033746,2015,762,-16,0.000000e+00,762.0,inf
41927,E01033746,2016,770,8,-3.602607e-11,770.0,-2.137341e+13
41928,E01033746,2017,768,-2,1.000000e+00,767.0,7.680000e+02
41929,E01033746,2018,782,14,0.000000e+00,782.0,inf
41930,E01033746,2019,781,-1,0.000000e+00,781.0,inf

In [88]:
# Calculate address_added
merged_df = merged_df.sort_values(by=['lsoa', 'year'])
# Unique LSOA codes
lsoa_list = merged_df['lsoa'].unique()

# Create figure
fig = go.Figure()

# Default LSOA
default_lsoa = lsoa_list[0]
df_filtered = merged_df[merged_df['lsoa'] == default_lsoa]

# Add all three default traces
fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['address_count'],
    mode='lines+markers',
    name='Address Count'
))

fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['address_added'],
    mode='lines+markers',
    name='Address Added'
))

fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['unit_count'],
    mode='lines+markers',
    name='Unit Count'
))

# Dropdown buttons
dropdown_buttons = []

for lsoa in lsoa_list:
    df_temp = merged_df[merged_df['lsoa'] == lsoa]
    
    dropdown_buttons.append(
        dict(
            method='update',
            label=lsoa,
            args=[
                {
                    'x': [df_temp['year'], df_temp['year'], df_temp['year']],
                    'y': [df_temp['address_count'], df_temp['address_added'], df_temp['unit_count']]
                },
                {
                    'title': f"Address Count, Added, and Unit Count — {lsoa}"
                }
            ]
        )
    )

# Layout
fig.update_layout(
    title=f"Address Count, Added, and Unit Count — {default_lsoa}",
    xaxis_title="Year",
    yaxis_title="Count",
    updatemenus=[{
        "buttons": dropdown_buttons,
        "direction": "down",
        "showactive": True,
        "x": 0.1,
        "xanchor": "left",
        "y": 1.15,
        "yanchor": "top"
    }]
)

fig.show()

In [61]:
merged_df

,lsoa,year,address_count,address_added,unit_count,address_minus_units,address_to_unit_ratio
0,E01000001,2011,1067,1067,1.012000e+03,55.0,1.054348e+00
1,E01000001,2012,1067,0,0.000000e+00,1067.0,inf
2,E01000001,2013,1067,0,0.000000e+00,1067.0,inf
3,E01000001,2014,1070,3,3.000000e+00,1067.0,3.566667e+02
4,E01000001,2015,1070,0,-1.000000e+00,1071.0,-1.070000e+03
...,...,...,...,...,...,...,...
41926,E01033746,2015,762,-16,0.000000e+00,762.0,inf
41927,E01033746,2016,770,8,-3.602607e-11,770.0,-2.137341e+13
41928,E01033746,2017,768,-2,1.000000e+00,767.0,7.680000e+02
41929,E01033746,2018,782,14,0.000000e+00,782.0,inf
41930,E01033746,2019,781,-1,0.000000e+00,781.0,inf

In [81]:
merged_df_filtered = merged_df[['lsoa','year','address_added','unit_count']]
merged_df_filtered = merged_df_filtered.round()

In [82]:
merged_df_filtered

            lsoa  year  address_added  unit_count
0      E01000001  2011           1067      1012.0
1      E01000001  2012              0         0.0
2      E01000001  2013              0         0.0
3      E01000001  2014              3         3.0
4      E01000001  2015              0        -1.0
...          ...   ...            ...         ...
41926  E01033746  2015            -16         0.0
41927  E01033746  2016              8        -0.0
41928  E01033746  2017             -2         1.0
41929  E01033746  2018             14         0.0
41930  E01033746  2019             -1         0.0

[41931 rows x 4 columns]

In [85]:
#Compute correlation per LSOA
correlation_per_lsoa = merged_df_filtered.groupby('lsoa').apply(
    lambda g: g['address_added'].corr(g['unit_count'])
).reset_index(name='correlation')


merged_df_with_corr = merged_df_filtered.merge(correlation_per_lsoa, on='lsoa')

/var/folders/k7/sydv9mbx0kz7fx7373rx_2100000gp/T/ipykernel_88393/2113869463.py:2: FutureWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [86]:
merged_df_with_corr

            lsoa  year  address_added  unit_count  correlation
0      E01000001  2011           1067      1012.0     0.999844
1      E01000001  2012              0         0.0     0.999844
2      E01000001  2013              0         0.0     0.999844
3      E01000001  2014              3         3.0     0.999844
4      E01000001  2015              0        -1.0     0.999844
...          ...   ...            ...         ...          ...
41926  E01033746  2015            -16         0.0     0.998351
41927  E01033746  2016              8        -0.0     0.998351
41928  E01033746  2017             -2         1.0     0.998351
41929  E01033746  2018             14         0.0     0.998351
41930  E01033746  2019             -1         0.0     0.998351

[41931 rows x 5 columns]

In [92]:
fig = px.histogram(merged_df_with_corr, x="correlation")
fig.show()

In [87]:
# Find most and least similar LSOAs
most_similar = merged_df_with_corr.sort_values('correlation', ascending=False).head()
most_different = merged_df_with_corr.sort_values('correlation', ascending=True).head()

print("Most Similar LSOAs:")
print(most_similar)

print("\nMost Different LSOAs:")
print(most_different)

Most Similar LSOAs:
           lsoa  year  address_added  unit_count  correlation
4035  E01000465  2014              0         0.0          1.0
4030  E01000464  2018              0         0.0          1.0
3944  E01000455  2013              0         0.0          1.0
3943  E01000455  2012              0         0.0          1.0
3942  E01000455  2011            619       619.0          1.0

Most Different LSOAs:
            lsoa  year  address_added  unit_count  correlation
41839  E01033736  2018              5        91.0     0.180231
41833  E01033736  2012              0      1066.0     0.180231
41834  E01033736  2013              0         0.0     0.180231
41835  E01033736  2014             92         0.0     0.180231
41836  E01033736  2015             91         0.0     0.180231

In [108]:
merged_df_with_corr_low_corr = merged_df_with_corr[merged_df_with_corr['correlation'] < 0.3]

In [109]:
merged_df_with_corr_low_corr['lsoa'].nunique()

2

In [110]:
merged_df_with_corr_low_corr

            lsoa  year  address_added  unit_count  correlation
33768  E01003933  2011            653       548.0     0.287375
33769  E01003933  2012            -24         3.0     0.287375
33770  E01003933  2013              0         0.0     0.287375
33771  E01003933  2014             -1        -1.0     0.287375
33772  E01003933  2015              2         2.0     0.287375
33773  E01003933  2016            756         5.0     0.287375
33774  E01003933  2017              2       283.0     0.287375
33775  E01003933  2018             -1         2.0     0.287375
33776  E01003933  2019              0       459.0     0.287375
41832  E01033736  2011            543       640.0     0.180231
41833  E01033736  2012              0      1066.0     0.180231
41834  E01033736  2013              0         0.0     0.180231
41835  E01033736  2014             92         0.0     0.180231
41836  E01033736  2015             91         0.0     0.180231
41837  E01033736  2016            204        92.0     0.180231
41838  E01033736  2017            223         0.0     0.180231
41839  E01033736  2018              5        91.0     0.180231
41840  E01033736  2019            141       355.0     0.180231

In [111]:
# Calculate address_added
merged_df = merged_df_with_corr_low_corr.sort_values(by=['lsoa', 'year'])
# Unique LSOA codes
lsoa_list = merged_df['lsoa'].unique()

# Create figure
fig = go.Figure()

# Default LSOA
default_lsoa = lsoa_list[0]
df_filtered = merged_df[merged_df['lsoa'] == default_lsoa]

# Add all three default traces

fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['address_added'],
    mode='lines+markers',
    name='Address Added'
))

fig.add_trace(go.Scatter(
    x=df_filtered['year'],
    y=df_filtered['unit_count'],
    mode='lines+markers',
    name='Unit Count'
))

# Dropdown buttons
dropdown_buttons = []

for lsoa in lsoa_list:
    df_temp = merged_df[merged_df['lsoa'] == lsoa]
    
    dropdown_buttons.append(
        dict(
            method='update',
            label=lsoa,
            args=[
                {
                    'x': [df_temp['year'], df_temp['year'], df_temp['year']],
                    'y': [df_temp['address_added'], df_temp['unit_count']]
                },
                {
                    'title': f"Address Count, Added, and Unit Count — {lsoa}"
                }
            ]
        )
    )

# Layout
fig.update_layout(
    title=f"Address Count, Added, and Unit Count — {default_lsoa}",
    xaxis_title="Year",
    yaxis_title="Count",
    updatemenus=[{
        "buttons": dropdown_buttons,
        "direction": "down",
        "showactive": True,
        "x": 0.1,
        "xanchor": "left",
        "y": 1.15,
        "yanchor": "top"
    }]
)

fig.show()